# Generated by Django 2.0 on 2020-05-23 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
                'permissions': (('can_view_bookings', 'can view bookings'),),
            },
        ),
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField(null='True')),
                ('endTime', models.DateTimeField(null='True')),
                ('status', models.IntegerField(default=1)),
                ('teacher', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timeslots',
                'permissions': (('can_view_time_slots', 'can view time slots'),),
            },
        ),
        migrations.AddField(
            model_name='bookings',
            name='timeSlot',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='api_views.TimeSlots'),
        ),
    ]
