# Generated by Django 2.0 on 2020-05-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_views', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='bookingTime',
            field=models.DateTimeField(null='True'),
        ),
    ]
