# Generated by Django 2.0 on 2020-05-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_views', '0002_bookings_bookingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslots',
            name='dayDate',
            field=models.DateTimeField(null='True'),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='endTime',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='startTime',
            field=models.CharField(default='', max_length=255),
        ),
    ]
